---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Security Returns}
   \rfoot{\color{headergrey}Chapter 2}
   \lfoot{\color{headergrey}\thepage}
   \fancyfoot[C]{\rmfamily\color{headergrey}Financial Modeling}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 3.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(reshape2, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(quantmod, quietly = TRUE, warn.conflicts = FALSE)
library(xts, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

data.dir <- paste0(here::here(), "/datasets")

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

#### Returns

Case Study: IBM

```{r}
date.from <- "2010-12-31"; date.to <- "2013-12-31"

raw.IBM <- getSymbols("IBM", from = date.from, to = date.to, auto.assign = F)

raw.IBM$IBM.Return <- Delt(raw.IBM$IBM.Close)
raw.IBM$IBM.TotalReturn <- Delt(raw.IBM$IBM.Adjusted)
raw.IBM$LogReturn <- diff(log(raw.IBM$IBM.Adjusted))
```

```{r}
plot(raw.IBM$IBM.Adjusted)
```

```{r}
plot(raw.IBM$IBM.Return)
```

```{r}
plot(raw.IBM$IBM.TotalReturn)
```

```{r}
plot(raw.IBM$LogReturn)
```

```{r}
raw.IBM$GrossReturn <- 1 + raw.IBM$IBM.TotalReturn
raw.IBM[1, ]$GrossReturn <- 1
raw.IBM$GrossCumulative <- cumprod(raw.IBM$GrossReturn)
raw.IBM$NetCumulative <- raw.IBM$GrossCumulative - 1
```

```{r}
raw.IBM[nrow(raw.IBM), ]$NetCumulative

plot(raw.IBM$NetCumulative)
```

```{r}
raw.IBM$CumLog <- raw.IBM$LogReturn
raw.IBM[1, ]$CumLog <- 0

ibm.log.ret <- sum(raw.IBM$CumLog)
exp(ibm.log.ret) - 1
```

```{r}
raw.IBM$PrcReturn <- raw.IBM$IBM.Return
raw.IBM$TotReturn <- raw.IBM$IBM.TotalReturn

raw.IBM[1, ]$PrcReturn <- 0
raw.IBM[1, ]$TotReturn <- 0

ibm.prc.return <- cumprod(1 + raw.IBM$PrcReturn)
ibm.tot.return <- cumprod(1 + raw.IBM$TotReturn)

plot(ibm.prc.return, col = "blue")
lines(ibm.tot.return, col = "black")
title(main = "Price Return vs. Total Return")
```

```{r}
data.AMZN <- getSymbols("AMZN", from = date.from, to = date.to, auto.assign = F)

amzn.returns <- data.table(index(data.AMZN), Delt(data.AMZN$AMZN.Adjusted))
colnames(amzn.returns) <- c("Date", "Return")

amzn.returns[1, ]$Return <- 0

amzn.returns$CumReturn <- cumprod(1 + amzn.returns$Return)

wk <- data.AMZN; amzn.weekly <- to.weekly(wk)

AMZN.weekly <- Delt(wk$AMZN.Adjusted); AMZN.weekly <- amzn.weekly[-1]

```

```{r}
data.AMZN <- getSymbols("AMZN", from = date.from, to = date.to, auto.assign = F)
data.IBM <- getSymbols("IBM", from = date.from, to = date.to, auto.assign = F)
data.MSFT <- getSymbols("MSFT", from = date.from, to = date.to, auto.assign = F)
data.NFLX <- getSymbols("NFLX", from = date.from, to = date.to, auto.assign = F)
```

```{r}
multi <- data.table(Date = index(data.AMZN), data.AMZN$AMZN.Adjusted, data.IBM$IBM.Adjusted, data.MSFT$MSFT.Adjusted, data.NFLX$NFLX.Adjusted)

names(multi) <- c("Date", "AMZN", "IBM", "MSFT", "NFLX")

multi.growth <- data.table(Date = multi$Date, apply(multi[, !"Date"], 2, function(x) x / x[1]))
```

```{r}
multi.growth.long <- reshape2::melt(multi.growth, id.vars = "Date")

ggplot(multi.growth.long, aes(Date, value, group = variable)) +
   geom_line(aes(col = variable)) +
   labs("Growth of $1 over Period")
```

