---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Portfolio Returns}
   \rfoot{\color{headergrey}Chapter 1}
   \lfoot{\color{headergrey}\thepage}
   \fancyfoot[C]{\rmfamily\color{headergrey}Financial Modeling}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 3.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(quantmod, quietly = TRUE, warn.conflicts = FALSE)
library(xts, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

data.dir <- paste0(here::here(), "/datasets")

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

#### Portfolio Returns

### Long Way

```{r}
investment.amounts <- c(AMZN = 50e3, MSFT = 10e3, NFLX = 30e3, IBM = 10e3)
portfolio.names <- c("AMZN", "MSFT", "NFLX", "IBM")
date.from <- '2010-12-31'; date.to <- '2014-1-1'

getSymbols(portfolio.names, from = date.from, to = date.to, auto.assign = T)

n <- nrow(AMZN)

combined.prices <- data.table(AMZN = AMZN[c(1, n), 6], 
                              MSFT = MSFT[c(1, n), 6],
                              NFLX = NFLX[c(1, n), 6],
                              IBM = IBM[c(1, n), 6])
colnames(combined.prices) <- portfolio.names

period.return <- data.table(apply(combined.prices, 2, Delt))
period.return <- period.return[2]

portfolio.weights <- investment.amounts / sum(investment.amounts)

portfolio.return <- sum(period.return * portfolio.weights)
```

Portfolio Return over the Period: `r round(portfolio.return, 4)*100`%

### Matrix Algebra

```{r}
wgt.mat <- t(as.matrix(portfolio.weights))
ret.mat <- t(as.matrix(period.return))

port.ret <- wgt.mat %*% ret.mat
```

Portfolio Return over the Period: `r round(port.ret, 4)*100`%

### Benchmark Returns

### Benchmark Portfolios

Benchmark Portfolio with 3 names

```{r}
benchmark.names <- c("AMZN", "MSFT", "IBM")
benchmark.prices <- data.table(Date = index(AMZN),
                              AMZN = AMZN[, 6],
                              MSFT = MSFT[, 6],
                              IBM = IBM[, 6])
colnames(benchmark.prices) <- c("Date", benchmark.names)


ewport <- benchmark.returns <- data.table(Date = index(AMZN), apply(benchmark.prices[, 2:4], 2, Delt))
ewport <- ewport[Date >= '2012-12-31' &
        Date <= '2013-12-31',]
rownames(ewport) <- seq(1:nrow(ewport))

ewport

ewport$AMZN <- 1 + ewport$AMZN
ewport$MSFT <- 1 + ewport$MSFT
ewport$IBM <- 1 + ewport$IBM

# Q1

ew.q1 <- subset(ewport,
                ewport$Date >= as.Date("2012-12-31") &
                ewport$Date <= as.Date("2013-03-31"))

ew.q1[1, 2:4] <- 1
ew.cum.q1 <- ew.q1[, lapply(.SD, cumprod), .SDcols = benchmark.names][, Date := ew.q1$Date]

num.sec <- length(colnames(ew.q1)) - 1

ew.idx.q1 <- ew.cum.q1[, lapply(.SD, function(x)(1/num.sec)*x), .SDcols = benchmark.names][, Date := ew.q1$Date]
ew.idx.q1[, Value := AMZN + MSFT + IBM]

# Q2

ew.q2 <- subset(ewport,
                ewport$Date >= as.Date("2013-3-31") &
                ewport$Date <= as.Date("2013-6-30"))

q2.value <- tail(ew.idx.q1, 1)$Value

ew.cum.q2 <- ew.q2[, lapply(.SD, cumprod), .SDcols = benchmark.names][, Date := ew.q2$Date]

ew.idx.q2 <- ew.cum.q2[, lapply(.SD, function(x)(q2.value/num.sec)*x), .SDcols = benchmark.names][, Date := ew.q2$Date]
ew.idx.q2[, Value := AMZN + MSFT + IBM]

# Q3

ew.q3 <- subset(ewport,
                ewport$Date >= as.Date("2013-6-30") &
                ewport$Date <= as.Date("2013-9-30"))

q3.value <- tail(ew.idx.q2, 1)$Value

ew.cum.q3 <- ew.q3[, lapply(.SD, cumprod), .SDcols = benchmark.names][, Date := ew.q3$Date]

ew.idx.q3 <- ew.cum.q3[, lapply(.SD, function(x)(q3.value/num.sec)*x), .SDcols = benchmark.names][, Date := ew.q3$Date]
ew.idx.q3[, Value := AMZN + MSFT + IBM]

# Q4

ew.q4 <- subset(ewport,
                ewport$Date >= as.Date("2013-9-30") &
                ewport$Date <= as.Date("2013-12-31"))

q3.value <- tail(ew.idx.q3, 1)$Value

ew.cum.q4 <- ew.q4[, lapply(.SD, cumprod), .SDcols = benchmark.names][, Date := ew.q4$Date]

ew.idx.q4 <- ew.cum.q4[, lapply(.SD, function(x)(q3.value/num.sec)*x), .SDcols = benchmark.names][, Date := ew.q4$Date]
ew.idx.q4[, Value := AMZN + MSFT + IBM]

```

```{r}

benchmark.returns <- data.table(Date = index(AMZN), apply(benchmark.prices[, 2:4], 2, Delt))
benchmark.returns[, ':='(Year = year(Date), Quarter = quarter(Date), Month = month(Date))]
benchmark.returns[1, c(2:4)] <- 0

benchmark.cumret <- benchmark.returns
benchmark.cumret[, ':='(AMZN = AMZN + 1, MSFT = MSFT + 1, IBM = IBM + 1)]
quarterly.returns <- benchmark.cumret[, lapply(.SD, cumprod), 
                  by = list(Year, Quarter), 
                  .SDcols = benchmark.names][, Date := benchmark.returns$Date]
rownames(quarterly.returns) <- seq(1:nrow(quarterly.returns))

n.sec <- 3

quarterly.returns[, lapply(.SD, function(x) c(head(x, 1), tail(x, 1))), 
                  by = list(Year, Quarter),
                  .SDcols = "Date"]
```

```{r}
ew.port.value <- rbind(ew.idx.q1[, .(Date, Value)],
                 ew.idx.q2[, .(Date, Value)],
                 ew.idx.q3[, .(Date, Value)],
                 ew.idx.q4[, .(Date, Value)])
```

```{r}
ggplot(ew.port.value[, Quarter := quarter(Date)], aes(Date, Value)) +
   geom_line(aes(col = Quarter))
```

```{r}
ewport$Quarter <- quarter(ewport$Date)

ewport <- ewport[2:nrow(ewport)]

```

