---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Markowitz Mean-Variance Optimization}
   \rfoot{\color{headergrey}Chapter 7}
   \lfoot{\color{headergrey}\thepage}
   \fancyfoot[C]{\rmfamily\color{headergrey}Financial Modeling}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 3.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(quantmod, quietly = TRUE, warn.conflicts = FALSE)
library(xts, quietly = TRUE, warn.conflicts = FALSE)
library(quadprog, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

data.dir <- file.path(here::here(), "Financial Modeling", "data")

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

## Markowitz Mean-Variance Optimization

Hypothetical Portfolio of SPY and SPAB

```{r}
names <- c("SPY", "SPAB")
date.from <- "2010-12-31"; date.to <- "2013-12-31"

getMonthlyReturns <- function(name, from = date.from, to = date.to) {
   prices <- getSymbols(name, from = date.from, to = date.to, auto.assign = F)
   monthly <- to.monthly(prices)
   returns <- Delt(monthly[, 6])[-1]
   
   ret.data <- data.table(Month = index(returns), Company = name, Return = returns[, 1])
   colnames(ret.data) <- c("Month", "Company", "Return")
   
   return(ret.data)
}

returns <- data.table::rbindlist(lapply(names, getMonthlyReturns))

portfolio <- dcast(returns, Month ~ Company, value.var = c("Return"))

portfolio.avg <- apply(portfolio[, 2:3], 2, mean)
portfolio.sd <- apply(portfolio[, 2:3], 2, sd)
portfolio.covar <- cov(portfolio[, 2:3])[1, 1]

portfolio.wgt.spy <- data.table(Weight = seq(0, 1, by = 0.01))
portfolio.wgt.spab <- 1 - portfolio.wgt.spy

portfolio.weights <- cbind(Wgt.SPY = portfolio.wgt.spy, Wgt.SPAB = portfolio.wgt.spab)

portfolio.returns <- portfolio.weights$Wgt.SPY.Weight * portfolio.avg[2] + portfolio.weights$Wgt.SPAB.Weight * portfolio.avg[1]
portfolio.risk <- portfolio.weights$Wgt.SPY.Weight * portfolio.sd[2] + portfolio.weights$Wgt.SPAB.Weight * portfolio.sd[1]

portfolio.profiles <- cbind(portfolio.weights, portfolio.returns, portfolio.risk)

portfolio.profiles[which.min(portfolio.profiles$portfolio.risk)]
```

```{r}
riskFree <- 0.007/12

portfolio.Sharpe <- (portfolio.returns - riskFree) / portfolio.risk

port.stats <- data.table(SPY.Wgt = portfolio.wgt.spy,
                         SPAB.Wgt = portfolio.wgt.spab,
                         Return = portfolio.returns,
                         Risk = portfolio.risk,
                         Sharpe = portfolio.Sharpe)

port.stats[which.max(port.stats$Sharpe)]

ggplot(port.stats, aes(Risk, Return)) +
   geom_point() +
   labs(title = "Mean-Variance Efficient Frontier of Two Assets (Long Way)")
```

### Quadratic Way

```{r}
mat.ret <- as.matrix(portfolio[, 2:3])

tail(mat.ret)

VCOV <- cov(mat.ret)

avg.ret <- matrix(apply(mat.ret, 2, mean))
colnames(avg.ret) <- paste("Avg.Ret")
rownames(avg.ret) <- paste(c("Lag", "Spy"))

min.ret <- min(avg.ret)
max.ret <- max(avg.ret)

increments <- 100
tgt.ret <- seq(min.ret, max.ret, length = increments)

head(tgt.ret)

tail(tgt.ret)

tgt.sd <- rep(0, length = increments)
tgt.sd

wgt <- matrix(0, nrow=increments, ncol = length(avg.ret))

head(wgt)

for(i in 1:increments){
   Dmat <- 2*VCOV
   dvec <- c(rep(0, length(avg.ret)))
   Amat <- cbind(rep(1, length(avg.ret)), avg.ret, diag(1, nrow=2))
   bvec <- c(1, tgt.ret[i], rep(0, 2))
   soln <- solve.QP(Dmat, dvec, Amat, bvec=bvec, meq=2)
   tgt.sd[i] <- sqrt(soln$value)
   wgt[i, ] <- soln$solution
}

head(tgt.sd)
tail(tgt.sd)

head(wgt)

colnames(wgt) <- c("Lag", "Spy")
tgt.port <- data.table(cbind(tgt.ret, tgt.sd, wgt))

min.var <- tgt.port[which.min(tgt.port$tgt.sd)]
max.ret <- tgt.port[which.max(tgt.port$tgt.ret)]

ggplot(tgt.port, aes(tgt.sd, tgt.ret)) +
   geom_point(col = "cornflowerblue") +
   geom_point(data = min.var, aes(x = tgt.sd, y = tgt.ret), col = "darkgreen", size = 4) +
   geom_point(data = max.ret, aes(x = tgt.sd, y = tgt.ret), col = "darkred", size = 4) +
   labs(title = "Efficent Frontier")
```

