---
title: ''
mainfont: Arial
fontsize: 12pt
documentclass: report
header-includes:
- \PassOptionsToPackage{table}{xcolor}
- \usepackage{caption}
- \usepackage{amssymb}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage[table]{xcolor}
- \usepackage{fancyhdr}
- \usepackage{boldline}
- \usepackage{tipa}
   \definecolor{headergrey}{HTML}{545454}
   \pagestyle{fancy}
   \setlength\headheight{30pt}
   \rhead{\color{headergrey}\today}
   \fancyhead[L]{\color{headergrey}Moretz, Brandon}
   \fancyhead[C]{\Large\bfseries\color{headergrey}Options}
   \rfoot{\color{headergrey}Chapter 9}
   \lfoot{\color{headergrey}\thepage}
   \fancyfoot[C]{\rmfamily\color{headergrey}Financial Modeling}
geometry: left = 1cm, right = 1cm, top = 2cm, bottom = 3cm
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r knitr_setup, include = FALSE}

knitr::opts_chunk$set(
   echo = T, 
   eval = TRUE, 
   dev = 'png', 
   fig.width = 9, 
   fig.height = 3.5)

options(knitr.table.format = "latex")

```

```{r report_setup, message = FALSE, warning = FALSE, include = FALSE}

library(data.table, quietly = TRUE, warn.conflicts = FALSE)
library(ggthemes, quietly = TRUE, warn.conflicts = FALSE)
library(scales, quietly = TRUE, warn.conflicts = FALSE)

library(knitr, quietly = TRUE, warn.conflicts = FALSE)
library(kableExtra, quietly = TRUE, warn.conflicts = FALSE)
library(pander, quietly = TRUE, warn.conflicts = FALSE)
library(formattable, quietly = TRUE, warn.conflicts = FALSE)

library(grid, quietly = TRUE, warn.conflicts = FALSE)
library(gridExtra, quietly = TRUE, warn.conflicts = FALSE)
library(extrafont, quietly = TRUE, warn.conflicts = FALSE)
library(tinytex, quietly = TRUE, warn.conflicts = FALSE)

library(quantmod, quietly = TRUE, warn.conflicts = FALSE)
library(xts, quietly = TRUE, warn.conflicts = FALSE)
library(quadprog, quietly = TRUE, warn.conflicts = FALSE)

library(here, quietly = TRUE, warn.conflicts = FALSE)

options(tinytex.verbose = TRUE)
suppressMessages(library("tidyverse"))

pretty_kable <- function(data, title, dig = 2) {
  kable(data, caption = title, digits = dig) %>%
    kable_styling(bootstrap_options = c("striped", "hover")) %>%
      kableExtra::kable_styling(latex_options = "hold_position")
}

theme_set(theme_light())

# Theme Overrides
theme_update(axis.text.x = element_text(size = 10),
             axis.text.y = element_text(size = 10),
             plot.title = element_text(hjust = 0.5, size = 16, face = "bold", color = "darkgreen"),
             axis.title = element_text(face = "bold", size = 12, colour = "steelblue4"),
             plot.subtitle = element_text(face = "bold", size = 8, colour = "darkred"),
             legend.title = element_text(size = 12, color = "darkred", face = "bold"),
             legend.position = "right", legend.title.align=0.5,
             panel.border = element_rect(linetype = "solid", 
                                         colour = "lightgray"), 
             plot.margin = unit(c( 0.1, 0.1, 0.1, 0.1), "inches"))

data.dir <- file.path(here::here(), "Financial Modeling", "data")

```

```{r pander_setup, include = FALSE}

knitr::opts_chunk$set(comment = NA)

panderOptions('table.alignment.default', function(df)
    ifelse(sapply(df, is.numeric), 'right', 'left'))
panderOptions('table.split.table', Inf)
panderOptions('big.mark', ",")
panderOptions('keep.trailing.zeros', TRUE)

```

## Options


```{r}
expry.date <- "2020-05-08"
   
options <- getOptionChain("AMZN", Exp = expry.date)

options

calls <- options$calls
calls

puts <- options$puts
puts
```

```{r}
calls <- options$calls[, c(1:2, 6)]

AMZN <- getSymbols("AMZN", from = "2020-3-30", to = "2020-3-31", auto.assign = F)

last <- AMZN$AMZN.Close

```

### Volatility

```{r}
AMZN <- getSymbols("AMZN", from = "2017-3-30", to = "2020-3-31", auto.assign = F)

volatility <- data.table(AMZN$AMZN.Adjusted)
colnames(volatility) <- c("Adj")

volatility$Ret <- c(NA, diff(log(volatility$Adj)))

hist.vol <- sd(volatility[-1]$Ret) * sqrt(252)
hist.vol
```

```{r}
price <- as.numeric(last$AMZN.Close)

call.delta <- abs(calls$Strike - price)
closest.calls <- head(sort(call.delta), 2)

bs.call <- calls[call.delta == closest.calls, 1:2]

put.delta <- abs(puts$Strike - price)
closest.puts <- head(sort(put.delta), 2)

bs.put <- puts[closest.puts, 1:2]

TTM <- as.numeric(as.Date(expry.date) - as.Date("2020-3-31"))

```

```{r}
rfr <- 0.0007

d1 <- (log(price/bs.call$Strike) + (rfr+0.5*(hist.vol^2)) * TTM)/(hist.vol*sqrt(TTM))
d2 <- d1 - hist.vol * sqrt(TTM)

bs.call$optval <- price * pnorm(d1, mean = 0, sd = 1) -
   bs.call$Strike * exp(-rfr * TTM) * pnorm(d2, mean = 0, sd = 1)

nd1 =- d1
nd1

nd2 =- d2
nd2

bs.put$optval <- bs.put$Strike *
   exp(-rfr*TTM)*pnorm(nd2, mean = 0, sd = 1) -
   price * pnorm(nd1, mean = 0, sd = 1)

bs.put
```

### Black-Scholes-Merton OPM Function

```{r}
bsm.option <- function(S, K, T, riskfree, sigma, type) {
   d1 <- (log(S/K) + (riskfree + 0.5*sigma^2)*T)/(sigma * sqrt(T))
   d2 <- d1 - sigma * sqrt(T)
   if(type == "C") {
      opt.val <- S * pnorm(d1) - K * exp(-riskfree*T) * pnorm(d2)
   }
   if(type == "P") {
      opt.val <- K * exp(-riskfree*T)*pnorm(-d2)-S*pnorm(-d1)
   }
   
   opt.val
}

cbind(bs.call, BSM = bsm.option(bs.call$Strike, price, TTM, rfr, hist.vol, "C"))

cbind(bs.put, BSM = bsm.option(bs.put$Strike, price, TTM, rfr, hist.vol, "P"))
```

### Put-Call Parity

```{r}
bs.call$optval.pcparity <- bs.put$optval - bs.put$Strike * exp(-rfr * TTM) + price
bs.call

bs.put$optval.pcparity <- bs.call$optval + bs.call$Strike * exp(-rfr * TTM) - price
bs.put
```

### The Greeks

```{r}
greeks.call <- bs.call[, 1:2]
greeks.call$delta <- pnorm(d1, mean=0, sd = 1)
greeks.call$gamma <- dnorm(d1, mean = 0, sd = 1) / (price*hist.vol*sqrt(TTM))
greeks.call$vega <- price * dnorm(d1, mean = 0, sd = 1) * sqrt(TTM)
greeks.call$theta <- -((price*hist.vol*dnorm(d1, mean =0, sd = 1)) /
   (2*sqrt(TTM))) - (rfr*greeks.call$Strike*exp(-rfr*TTM) * 
      pnorm(d2))
greeks.call$rho <- greeks.call$Strike * TTM * exp(-rfr * TTM) *
   pnorm(d2)
greeks.call$type <- c("call")

greeks.call
```


```{r}
greeks.put <- bs.put[, 1:2]
greeks.put$delta <- pnorm(d1) - 1
greeks.put$gamma <- dnorm(d1) / (price*hist.vol*sqrt(TTM))
greeks.put$vega <- price * dnorm(d1) * sqrt(TTM)
greeks.put$theta <- -((price*hist.vol*dnorm(d1))/2*sqrt(TTM)) + 
   (rfr*greeks.put$Strike*exp(-rfr*TTM)) *
   pnorm(nd2)
greeks.put$rho <- -greeks.put$Strike * TTM * exp(-rfr * TTM)
greeks.put$type <- c("put")

greeks.put
```

### Implied Volatility

```{r}
iv.opt <- function(S, K, T, riskfree, price, type) {
   sigma <- hist.vol
   sigma.up <- 1
   sigma.down <- 0.001
   count <- 0
   epsilon <- bsm.option(S, K, TTM, riskfree, sigma, type) - price
   while(abs(epsilon) > 0.00001 && count < 1000) {
      if(epsilon < 0) {
         sigma.down <- -sigma
         sigma <- (sigma.up + sigma)/2
      } else {
         sigma.up <- sigma
         sigma <- (sigma.down+sigma)/2
      }
      epsilon <- bsm.option(S, K, TTM, riskfree, sigma, type) - price
      count <- count + 1
   
      if(count == 1000) {
         return(NA)
      } else {
         return(sigma)  
      }
   }
}

bs.call

iv.opt(price, 1935, TTM, rfr, 1280.417, "C")
```

### Market Risk

```{r}
vix_raw <- data.table::fread(file.path(data.dir, "VIXCLS.csv"))

vix_raw$DATE <- as.Date(vix_raw$DATE)
vix_raw$VIXCLS <- as.numeric(vix_raw$VIXCLS)

colnames(vix_raw) <- c("Date", "Price")

vix_raw <- na.omit(vix_raw)
vix_raw
```

```{r}
spx_raw <- data.table::fread(file.path(data.dir, "SP500.csv"))

spx_raw$DATE <- as.Date(spx_raw$DATE)
spx_raw$SP500 <- as.numeric(spx_raw$SP500)

colnames(spx_raw) <- c("Date", "Price")

spx_raw <- na.omit(spx_raw)

spx_raw
```

```{r}
spx <- data.table(Date = spx_raw$Date, 
                  Return = c(NA, diff(log(spx_raw$Price))))
vix <- data.table(Date = vix_raw$Date,
                  Return = c(NA, diff(log(vix_raw$Price))))
```

```{r}
spx$sd <- c(rep(NA, 29), rollapply(spx$Return, 30, sd, na.rm = T) * sqrt(252) * 100)
vix$sd <- c(rep(NA, 29), rollapply(vix$Return, 30, sd, na.rm = T) * sqrt(252) * 100)

combined <- merge(spx, vix, by = "Date")
colnames(combined) <- c("Date", "SPX", "SPX.Vol", "VIX", "VIX.Vol")

combined
``` 

```{r}
ggplot(combined) +
   geom_line(data = vix_raw, aes(Date, Price), col = "darkgreen") +
   geom_line(aes(Date, VIX.Vol), col = "darkred")
```

### Binomial OPM

```{r}

```

